"use client";

import { useEffect, useMemo, useState } from "react";
import { Ban, Check, Clock3, RefreshCw, Search, ShieldAlert, ShieldCheck, Undo2, UserMinus, Users } from "lucide-react";

type Evidence = { category?: string; source?: string; label?: string; excerpt?: string };
type QueueItem = { did:string;handle?:string;display_name?:string;avatar?:string;description?:string;followers_count?:number;follows_count?:number;is_following?:boolean;last_activity_at?:string;score?:number;categories?:string[];confidence?:string;evidence?:Evidence[] };
type Dashboard = { user?:any;settings?:any;queue?:QueueItem[];suppressions?:any[];actions?:any[];scan?:any;counts?:any };

const labels:Record<string,string>={inactive:"Inactive",bot_spam:"Bot / spam",right_wing_explicit:"Explicit right-wing profile",anti_palestine:"Anti-Palestinian content",islamophobia:"Islamophobic content",xenophobia:"Xenophobic content"};

async function api(method:"GET"|"POST"="GET", body?:any){
  const r=await fetch("/api/guard",{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});
  const j=await r.json(); if(!r.ok) throw new Error(j.error||"Guard request failed."); return j;
}
function fmtDate(value?:string){if(!value)return "—";const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString():"—";}

export function IazmaGuardDashboard(){
  const [data,setData]=useState<Dashboard>({}); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(""); const [error,setError]=useState(""); const [tab,setTab]=useState<"review"|"suppression"|"history"|"settings">("review");
  const refresh=async()=>{try{setError("");setData(await api());}catch(e){setError(e instanceof Error?e.message:"Could not load Guard.");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const queue=data.queue??[]; const stats=useMemo(()=>[{label:"Followers",value:data.counts?.followers??0,icon:Users},{label:"Following",value:data.counts?.following??0,icon:UserMinus},{label:"Review",value:queue.length,icon:ShieldAlert},{label:"Observed unfollows",value:data.counts?.observed_unfollowers??0,icon:Clock3}], [data,queue.length]);
  const runScan=async()=>{setWorking("scan");setError("");try{const started=await api("POST",{action:"scan_start"});let state:any={status:started.total?"running":"complete",id:started.scanId};while(state.status!=="complete"){state=await api("POST",{action:"scan_batch",scanId:started.scanId,limit:8});}await refresh();}catch(e){setError(e instanceof Error?e.message:"Scan failed.");}finally{setWorking("");}};
  const action=async(kind:string,did:string)=>{setWorking(`${kind}:${did}`);setError("");try{await api("POST",{action:kind,did});await refresh();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setWorking("");}};
  const sync=async()=>{setWorking("sync");try{await api("POST",{action:"sync"});await refresh();}catch(e){setError(e instanceof Error?e.message:"Sync failed.");}finally{setWorking("");}};
  const saveSettings=async(form:FormData)=>{setWorking("settings");try{await api("POST",{action:"settings",inactive_days:Number(form.get("inactive_days")),bot_threshold:Number(form.get("bot_threshold")),auto_unfollow:form.get("auto_unfollow")==="on",filters:{rightWing:form.get("rightWing")==="on",antiPalestine:form.get("antiPalestine")==="on",islamophobia:form.get("islamophobia")==="on",xenophobia:form.get("xenophobia")==="on"}});await refresh();}catch(e){setError(e instanceof Error?e.message:"Settings failed.");}finally{setWorking("");}};
  if(loading)return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-8 text-sm text-white/50">Loading Guard…</div>;
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stats.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><Icon className="size-4 text-[#8ce8ff]"/><div className="mt-5 text-3xl font-semibold">{value}</div><div className="mt-1 text-xs uppercase tracking-[0.12em] text-white/40">{label}</div></div>)}</div>
    <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><button onClick={()=>void runScan()} disabled={!!working} className="rounded-xl bg-[#16c8ff] px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50"><Search className="mr-2 inline size-4"/>{working==="scan"?"Scanning…":"Scan followers"}</button><button onClick={()=>void sync()} disabled={!!working} className="rounded-xl border border-white/12 px-4 py-2.5 text-sm text-white/75"><RefreshCw className="mr-2 inline size-4"/>Sync graph</button><div className="ml-auto text-xs text-white/35">Last graph sync: {fmtDate(data.user?.last_graph_sync_at)}</div></div>
    {error?<div className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-100">{error}</div>:null}
    <div className="flex gap-1 overflow-x-auto rounded-xl border border-white/10 bg-black/25 p-1">{(["review","suppression","history","settings"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-4 py-2 text-sm capitalize ${tab===t?"bg-white/10 text-white":"text-white/45"}`}>{t}</button>)}</div>
    {tab==="review"?<div className="space-y-4">{queue.length===0?<Empty text="No accounts currently need review."/>:queue.map(item=><article key={item.did} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start"><div className="flex min-w-0 flex-1 gap-4">{item.avatar?<img src={item.avatar} alt="" className="size-12 rounded-full object-cover"/>:<div className="grid size-12 shrink-0 place-items-center rounded-full bg-white/10 text-lg">?</div>}<div className="min-w-0"><h2 className="truncate text-lg font-semibold">{item.display_name||`@${item.handle}`}</h2><p className="truncate text-sm text-white/45">@{item.handle}</p><div className="mt-3 flex flex-wrap gap-2">{(item.categories??[]).map(c=><span key={c} className="rounded-full border border-[#16c8ff]/20 bg-[#16c8ff]/8 px-2.5 py-1 text-xs text-[#9be9ff]">{labels[c]||c}</span>)}<span className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-white/45">score {item.score??0}</span>{item.is_following?<span className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-white/45">you follow them</span>:null}</div></div></div><div className="flex shrink-0 gap-2"><button onClick={()=>void action("ignore",item.did)} disabled={!!working} className="rounded-xl border border-white/12 px-3 py-2 text-sm text-white/65"><Check className="mr-1.5 inline size-4"/>Keep</button><button onClick={()=>void action("block",item.did)} disabled={!!working} className="rounded-xl bg-red-500/85 px-3 py-2 text-sm font-semibold text-white"><Ban className="mr-1.5 inline size-4"/>{item.is_following?"Unfollow + Block":"Block"}</button></div></div><div className="mt-5 grid gap-2">{(item.evidence??[]).map((e,i)=><div key={i} className="rounded-xl border border-white/8 bg-black/20 p-3"><div className="text-xs font-semibold text-white/70">{e.label||labels[e.category||""]||e.category}</div>{e.excerpt?<p className="mt-1 text-sm leading-6 text-white/48">“{e.excerpt}”</p>:null}<div className="mt-1 text-[11px] uppercase tracking-[0.1em] text-white/25">{e.source}</div></div>)}</div>{item.last_activity_at?<div className="mt-4 text-xs text-white/35">Last public activity: {fmtDate(item.last_activity_at)}</div>:null}</article>)}</div>:null}
    {tab==="suppression"?<div className="space-y-3">{(data.suppressions??[]).length===0?<Empty text="IAZMA suppression list is empty."/>:(data.suppressions??[]).map((s:any)=><div key={s.did} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="font-medium">@{s.handle||s.did}</div><div className="mt-1 text-sm text-white/45">{s.reason} · {s.source}</div></div><button onClick={()=>void action("restore",s.did)} className="rounded-lg border border-white/12 px-3 py-2 text-sm text-white/65"><Undo2 className="mr-1.5 inline size-4"/>Allow in IAZMA</button></div>)}</div>:null}
    {tab==="history"?<div className="overflow-hidden rounded-2xl border border-white/10">{(data.actions??[]).map((a:any)=><div key={a.id} className="grid gap-1 border-b border-white/8 p-4 last:border-0 sm:grid-cols-[1fr_auto]"><div><div className="text-sm font-medium">{a.action.replaceAll("_"," ")} · @{a.handle||a.target_did}</div><div className="mt-1 text-xs text-white/40">{a.reason}</div></div><div className="text-xs text-white/30">{fmtDate(a.created_at)}</div></div>)}</div>:null}
    {tab==="settings"?<form action={async(form)=>{await saveSettings(form)}} className="grid gap-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><label className="grid gap-2 text-sm text-white/65">Inactive threshold (days)<input name="inactive_days" type="number" min={30} max={365} defaultValue={data.settings?.inactive_days??90} className="rounded-xl border border-white/12 bg-black/25 px-3 py-2.5 text-white"/></label><label className="grid gap-2 text-sm text-white/65">Bot/spam threshold<input name="bot_threshold" type="number" min={50} max={95} defaultValue={data.settings?.bot_threshold??70} className="rounded-xl border border-white/12 bg-black/25 px-3 py-2.5 text-white"/></label><Toggle name="auto_unfollow" label="Automatically unfollow accounts that Guard observed following you and later detects as unfollowed" checked={data.settings?.auto_unfollow!==false}/><div className="border-t border-white/10 pt-4 text-xs uppercase tracking-[0.14em] text-white/35">Evidence review filters</div><Toggle name="rightWing" label="Explicit right-wing self-identification" checked={data.settings?.filters?.rightWing!==false}/><Toggle name="antiPalestine" label="Explicit anti-Palestinian content" checked={data.settings?.filters?.antiPalestine!==false}/><Toggle name="islamophobia" label="Explicit Islamophobic content" checked={data.settings?.filters?.islamophobia!==false}/><Toggle name="xenophobia" label="Explicit xenophobic content" checked={data.settings?.filters?.xenophobia!==false}/><button disabled={working==="settings"} className="w-fit rounded-xl bg-[#16c8ff] px-4 py-2.5 text-sm font-semibold text-black">Save settings</button><p className="text-xs leading-5 text-white/30"><ShieldCheck className="mr-1 inline size-3.5"/>Content filters flag explicit public evidence for review; they do not infer hidden ideology. Blocks are public AT Protocol records.</p></form>:null}
  </div>;
}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/12 p-8 text-center text-sm text-white/38">{text}</div>}
function Toggle({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-start gap-3 text-sm leading-6 text-white/60"><input name={name} type="checkbox" defaultChecked={checked} className="mt-1 size-4 accent-[#16c8ff]"/><span>{label}</span></label>}
