import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, GitBranch, LockKeyhole, Radar, Target, UsersRound } from "lucide-react";
import { AdvancedNetworkRequestForm } from "@/components/tools/advanced-network-request-form";
import { Badge } from "@/components/ui/badge";
import { buttonStyles } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { createPageMetadata } from "@/lib/site-config";

export const metadata: Metadata = createPageMetadata({
  title: "Advanced Bluesky Network Intelligence",
  description: "A private, paid Bluesky network-growth workspace that maps reciprocal paths to influential communities, tracks follow-backs, ranks relationship value, and recommends the next high-leverage connections.",
  path: "/tools/bluesky-network-advanced",
});

const features = [
  { icon: Target, title: "Aim the graph", text: "Target up to 10 specific profiles, categories like gaming or politics, or let the engine recommend the cheapest high-value direction." },
  { icon: GitBranch, title: "Mutual-path intelligence", text: "Find reciprocal paths through bridges, bridge besties, influential-account besties, and besties-of-besties — then run a second fresh influence wave." },
  { icon: UsersRound, title: "Follow-back tracking", text: "Remember every recommended follow, when you acted, who followed back, and which new mutual edge changed the graph the most." },
  { icon: BarChart3, title: "Dynamic importance", text: "Re-rank people as your network changes using distance, independent paths, cluster overlap, interaction strength, reach, relevance, and reciprocity." },
  { icon: Radar, title: "Engagement strategy", text: "Surface the people and public conversations worth engaging with when a high-value target has not followed back yet." },
  { icon: LockKeyhole, title: "Private workspace", text: "Paid access is gated. The customer must connect the Bluesky account the workspace belongs to before account-specific analysis begins." },
];

export default function AdvancedBlueskyNetworkPage() {
  return <>
    <Section className="relative overflow-hidden border-b border-white/10"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-[linear-gradient(90deg,transparent,#16c8ff_30%,#e6bd73_50%,#f0001c_70%,transparent)]"/><Container><Badge tone="blue">Private beta · Paid product · Request access</Badge><h1 className="mt-6 max-w-5xl text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-6xl lg:text-7xl">Engineer where your Bluesky network goes next.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/65 sm:text-xl">Advanced Network treats Bluesky as a changing relationship graph. Pick the people or communities you want to move toward, find the reciprocal paths already available to you, and measure whether each recommended connection actually improves your position.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#request-access" className={buttonStyles({ variant: "glass", size: "lg" })}>Request access<ArrowRight className="size-4" aria-hidden/></Link><Link href="/tools/bluesky-network-advanced/app" className={buttonStyles({ variant: "secondary", size: "lg" })}>Already approved? Open workspace</Link></div></Container></Section>
    <Section><Container><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{features.map((feature) => <Card key={feature.title} className="p-6"><feature.icon className="size-5 text-[#8ce8ff]" aria-hidden/><h2 className="mt-5 text-xl font-semibold text-white">{feature.title}</h2><p className="mt-3 text-sm leading-7 text-white/52">{feature.text}</p></Card>)}</div></Container></Section>
    <Section className="border-y border-white/10 bg-white/[0.012]"><Container className="grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#e6bd73]">The recursive engine</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">It does not stop at the celebrity.</h2><p className="mt-4 max-w-2xl text-base leading-8 text-white/58">A large account is both a destination and a node. The engine also maps that account&apos;s recurring mutual besties, those besties&apos; besties, your own followers who already bridge into that neighborhood, and then launches a second large-account search from the expanded graph.</p><ol className="mt-6 grid gap-3 text-sm text-white/58">{["Large-account wave #1", "Shortest reciprocal paths and missing bridges", "Bridge besties + large-account besties", "Besties-of-besties + warm follower bridges", "Follow-back outcomes + dynamic re-ranking", "Large-account wave #2 using the newly expanded graph"].map((item, index) => <li key={item} className="flex gap-3 rounded-xl border border-white/10 bg-black/10 px-4 py-3"><span className="font-mono text-[#ff7f8a]">0{index+1}</span>{item}</li>)}</ol></div><Card className="p-6 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8ce8ff]">Example target campaign</p><div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><p className="font-semibold text-white">Entertainment expansion</p><p className="mt-1 text-xs text-white/40">Specific targets + Film & TV category</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><span className="rounded-lg border border-white/10 p-3"><b className="block text-xl text-white">10</b><span className="text-white/38">targets entered</span></span><span className="rounded-lg border border-white/10 p-3"><b className="block text-xl text-white">6</b><span className="text-white/38">deep analysis</span></span><span className="rounded-lg border border-white/10 p-3"><b className="block text-xl text-white">4.7 → 3.2</b><span className="text-white/38">avg. target distance</span></span><span className="rounded-lg border border-white/10 p-3"><b className="block text-xl text-white">37%</b><span className="text-white/38">follow-back conversion</span></span></div></div><p className="mt-4 text-xs leading-5 text-white/35">Illustrative dashboard metrics. Real customer dashboards are calculated from their own saved graph history.</p></Card></Container></Section>
    <Section id="request-access"><Container className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><Badge tone="gold">Lead-gated access</Badge><h2 className="mt-5 text-3xl font-semibold text-white sm:text-4xl">Start with a private cohort.</h2><p className="mt-4 text-base leading-8 text-white/56">Access requests feed the existing Rukh Labs lead system. Early customers can be approved deliberately while graph costs, scoring, and plan limits are calibrated before opening the product more broadly.</p></div><AdvancedNetworkRequestForm/></Container></Section>
  </>;
}
